# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

# Common Properties
minecraft_version=1.21.6
enabled_platforms=fabric,neoforge

# Fabric Properties
# check this on https://fabricmc.net/develop
fabric_loader_version=0.18.4

# NeoForge Properties
# check this on https://neoforged.net
neoforge_version=21.6.20-beta

# Mod Properties
mod_version=1.1.0+mc1.21.6
maven_group=me.bjtmastermind.easy_data_fix
archives_base_name=easy_data_fix

# Dependencies
architectury_version=17.0.6
fabric_api_version=0.128.2+1.21.6