# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Environment Properties
java_version=25
minecraft_version=26.1
minecraft_version_range=[26.1,)

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_loader_version=0.19.3
fabric_api_version=0.145.1+26.1

# NeoForge, see https://neoforged.net for new versions
neoforge_version=26.1.0.19-beta

# Mod Properties
mod_id=easy_data_fix
mod_group=me.voxelbill.easy_data_fix
mod_version=1.2.0+mc26.1
mod_name=Easy Data Fix
mod_description=API support for data fixers
mod_license=MIT
mod_icon=icon.png
mod_github=https://github.com/VoxelBill/easy-data-fix