modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/BJTMastermind/easy-data-fix/issues"

[[mods]]
    modId="easy_data_fix"
    version="${version}"
    displayName="Easy Data Fix"
    authors="""BJTMastermind,
           QWERTY770 (Upstream Maintainer)"""
    description="""API support for data fixers"""
    displayURL="https://github.com/BJTMastermind/easy-data-fix"

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

[[mixins]]
    config="easy_data_fix.mixins.json"

[[dependencies.easy_data_fix]]
    modId="neoforge"
    type="required"
    versionRange="[21.6.20-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.easy_data_fix]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.6,)"
    ordering="NONE"
    side="BOTH"
