modLoader="javafml"
license="${mod_license}"
issueTrackerURL="${mod_github}/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="""VoxelBill (Formerly known as BJTMastermind),
           QWERTY770 (Upstream Maintainer)"""
    description="""${mod_description}"""
    displayURL="${mod_github}"
    logoFile="${mod_icon}"

[[mixins]]
    config="easy_data_fix.mixins.json"

[[dependencies.easy_data_fix]]
    modId="neoforge"
    type="required"
    versionRange="[${neoforge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.easy_data_fix]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"